/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivationRouteImport } from './routes/Activation'
import { Route as AddProductRouteImport } from './routes/AddProduct'
import { Route as AdminRouteImport } from './routes/Admin'
import { Route as AdminDashboardRouteImport } from './routes/AdminDashboard'
import { Route as CashBoxRouteImport } from './routes/CashBox'
import { Route as CreateShopRouteImport } from './routes/CreateShop'
import { Route as DashboardRouteImport } from './routes/Dashboard'
import { Route as KhataRouteImport } from './routes/Khata'
import { Route as PartyDetailRouteImport } from './routes/PartyDetail'
import { Route as ProductDetailRouteImport } from './routes/ProductDetail'
import { Route as ProductListRouteImport } from './routes/ProductList'
import { Route as ReportsRouteImport } from './routes/Reports'
import { Route as SaleRouteImport } from './routes/Sale'
import { Route as SalesLedgerRouteImport } from './routes/SalesLedger'
import { Route as SelectShopRouteImport } from './routes/SelectShop'
import { Route as SettingsRouteImport } from './routes/Settings'
import { Route as TransactionsRouteImport } from './routes/Transactions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/Activation',
  path: '/Activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProductRoute = AddProductRouteImport.update({
  id: '/AddProduct',
  path: '/AddProduct',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/AdminDashboard',
  path: '/AdminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBoxRoute = CashBoxRouteImport.update({
  id: '/CashBox',
  path: '/CashBox',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateShopRoute = CreateShopRouteImport.update({
  id: '/CreateShop',
  path: '/CreateShop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataRoute = KhataRouteImport.update({
  id: '/Khata',
  path: '/Khata',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyDetailRoute = PartyDetailRouteImport.update({
  id: '/PartyDetail',
  path: '/PartyDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/ProductDetail',
  path: '/ProductDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductListRoute = ProductListRouteImport.update({
  id: '/ProductList',
  path: '/ProductList',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/Reports',
  path: '/Reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/Sale',
  path: '/Sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerRoute = SalesLedgerRouteImport.update({
  id: '/SalesLedger',
  path: '/SalesLedger',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectShopRoute = SelectShopRouteImport.update({
  id: '/SelectShop',
  path: '/SelectShop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/Settings',
  path: '/Settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/Transactions',
  path: '/Transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Activation': typeof ActivationRoute
  '/AddProduct': typeof AddProductRoute
  '/Admin': typeof AdminRoute
  '/AdminDashboard': typeof AdminDashboardRoute
  '/CashBox': typeof CashBoxRoute
  '/CreateShop': typeof CreateShopRoute
  '/Dashboard': typeof DashboardRoute
  '/Khata': typeof KhataRoute
  '/PartyDetail': typeof PartyDetailRoute
  '/ProductDetail': typeof ProductDetailRoute
  '/ProductList': typeof ProductListRoute
  '/Reports': typeof ReportsRoute
  '/Sale': typeof SaleRoute
  '/SalesLedger': typeof SalesLedgerRoute
  '/SelectShop': typeof SelectShopRoute
  '/Settings': typeof SettingsRoute
  '/Transactions': typeof TransactionsRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Activation': typeof ActivationRoute
  '/AddProduct': typeof AddProductRoute
  '/Admin': typeof AdminRoute
  '/AdminDashboard': typeof AdminDashboardRoute
  '/CashBox': typeof CashBoxRoute
  '/CreateShop': typeof CreateShopRoute
  '/Dashboard': typeof DashboardRoute
  '/Khata': typeof KhataRoute
  '/PartyDetail': typeof PartyDetailRoute
  '/ProductDetail': typeof ProductDetailRoute
  '/ProductList': typeof ProductListRoute
  '/Reports': typeof ReportsRoute
  '/Sale': typeof SaleRoute
  '/SalesLedger': typeof SalesLedgerRoute
  '/SelectShop': typeof SelectShopRoute
  '/Settings': typeof SettingsRoute
  '/Transactions': typeof TransactionsRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Activation': typeof ActivationRoute
  '/AddProduct': typeof AddProductRoute
  '/Admin': typeof AdminRoute
  '/AdminDashboard': typeof AdminDashboardRoute
  '/CashBox': typeof CashBoxRoute
  '/CreateShop': typeof CreateShopRoute
  '/Dashboard': typeof DashboardRoute
  '/Khata': typeof KhataRoute
  '/PartyDetail': typeof PartyDetailRoute
  '/ProductDetail': typeof ProductDetailRoute
  '/ProductList': typeof ProductListRoute
  '/Reports': typeof ReportsRoute
  '/Sale': typeof SaleRoute
  '/SalesLedger': typeof SalesLedgerRoute
  '/SelectShop': typeof SelectShopRoute
  '/Settings': typeof SettingsRoute
  '/Transactions': typeof TransactionsRoute
  '/auth': typeof AuthRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Activation'
    | '/AddProduct'
    | '/Admin'
    | '/AdminDashboard'
    | '/CashBox'
    | '/CreateShop'
    | '/Dashboard'
    | '/Khata'
    | '/PartyDetail'
    | '/ProductDetail'
    | '/ProductList'
    | '/Reports'
    | '/Sale'
    | '/SalesLedger'
    | '/SelectShop'
    | '/Settings'
    | '/Transactions'
    | '/auth'
    | '/confirm-email'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Activation'
    | '/AddProduct'
    | '/Admin'
    | '/AdminDashboard'
    | '/CashBox'
    | '/CreateShop'
    | '/Dashboard'
    | '/Khata'
    | '/PartyDetail'
    | '/ProductDetail'
    | '/ProductList'
    | '/Reports'
    | '/Sale'
    | '/SalesLedger'
    | '/SelectShop'
    | '/Settings'
    | '/Transactions'
    | '/auth'
    | '/confirm-email'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/Activation'
    | '/AddProduct'
    | '/Admin'
    | '/AdminDashboard'
    | '/CashBox'
    | '/CreateShop'
    | '/Dashboard'
    | '/Khata'
    | '/PartyDetail'
    | '/ProductDetail'
    | '/ProductList'
    | '/Reports'
    | '/Sale'
    | '/SalesLedger'
    | '/SelectShop'
    | '/Settings'
    | '/Transactions'
    | '/auth'
    | '/confirm-email'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  AddProductRoute: typeof AddProductRoute
  AdminRoute: typeof AdminRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CashBoxRoute: typeof CashBoxRoute
  CreateShopRoute: typeof CreateShopRoute
  DashboardRoute: typeof DashboardRoute
  KhataRoute: typeof KhataRoute
  PartyDetailRoute: typeof PartyDetailRoute
  ProductDetailRoute: typeof ProductDetailRoute
  ProductListRoute: typeof ProductListRoute
  ReportsRoute: typeof ReportsRoute
  SaleRoute: typeof SaleRoute
  SalesLedgerRoute: typeof SalesLedgerRoute
  SelectShopRoute: typeof SelectShopRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  AuthRoute: typeof AuthRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Activation': {
      id: '/Activation'
      path: '/Activation'
      fullPath: '/Activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AddProduct': {
      id: '/AddProduct'
      path: '/AddProduct'
      fullPath: '/AddProduct'
      preLoaderRoute: typeof AddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminDashboard': {
      id: '/AdminDashboard'
      path: '/AdminDashboard'
      fullPath: '/AdminDashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CashBox': {
      id: '/CashBox'
      path: '/CashBox'
      fullPath: '/CashBox'
      preLoaderRoute: typeof CashBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CreateShop': {
      id: '/CreateShop'
      path: '/CreateShop'
      fullPath: '/CreateShop'
      preLoaderRoute: typeof CreateShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Khata': {
      id: '/Khata'
      path: '/Khata'
      fullPath: '/Khata'
      preLoaderRoute: typeof KhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PartyDetail': {
      id: '/PartyDetail'
      path: '/PartyDetail'
      fullPath: '/PartyDetail'
      preLoaderRoute: typeof PartyDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductDetail': {
      id: '/ProductDetail'
      path: '/ProductDetail'
      fullPath: '/ProductDetail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProductList': {
      id: '/ProductList'
      path: '/ProductList'
      fullPath: '/ProductList'
      preLoaderRoute: typeof ProductListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reports': {
      id: '/Reports'
      path: '/Reports'
      fullPath: '/Reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Sale': {
      id: '/Sale'
      path: '/Sale'
      fullPath: '/Sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SalesLedger': {
      id: '/SalesLedger'
      path: '/SalesLedger'
      fullPath: '/SalesLedger'
      preLoaderRoute: typeof SalesLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SelectShop': {
      id: '/SelectShop'
      path: '/SelectShop'
      fullPath: '/SelectShop'
      preLoaderRoute: typeof SelectShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Settings': {
      id: '/Settings'
      path: '/Settings'
      fullPath: '/Settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Transactions': {
      id: '/Transactions'
      path: '/Transactions'
      fullPath: '/Transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  AddProductRoute: AddProductRoute,
  AdminRoute: AdminRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CashBoxRoute: CashBoxRoute,
  CreateShopRoute: CreateShopRoute,
  DashboardRoute: DashboardRoute,
  KhataRoute: KhataRoute,
  PartyDetailRoute: PartyDetailRoute,
  ProductDetailRoute: ProductDetailRoute,
  ProductListRoute: ProductListRoute,
  ReportsRoute: ReportsRoute,
  SaleRoute: SaleRoute,
  SalesLedgerRoute: SalesLedgerRoute,
  SelectShopRoute: SelectShopRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  AuthRoute: AuthRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
